name: dbt Build and Deploy

on:
  workflow_dispatch: #Run manually when I update dbt pipeline 

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Install dbt dependencies
        run: cd levergreen_dbt && dbt deps

      - name: Run dbt models
        run: |
          cd levergreen_dbt
          mkdir -p logs
          echo "Running dbt models..."
          dbt run > logs/dbt_run_${GITHUB_RUN_NUMBER}.log 2>&1
          echo "dbt models run completed with status $?"
          cat logs/dbt_run_${GITHUB_RUN_NUMBER}.log
        env:
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PORT: ${{ secrets.PG_PORT }}
    
      - name: Generate dbt documentation
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd levergreen_dbt
          dbt docs generate --no-compile >> logs/dbt_run_${GITHUB_RUN_NUMBER}.log 2>&1
          cat logs/dbt_run_${GITHUB_RUN_NUMBER}.log
        env:
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PORT: 5432
  
      - name: Deploy to Github Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./levergreen_dbt/target
        
      - name: Test dbt models
        run: |
          cd levergreen_dbt
          dbt test >> logs/dbt_run_${GITHUB_RUN_NUMBER}.log 2>&1
          cat logs/dbt_run_${GITHUB_RUN_NUMBER}.log
        env:
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PORT: 5432
  
      - name: Check Freshness of dbt models
        run: |
          cd levergreen_dbt
          dbt source freshness >> logs/dbt_run_${GITHUB_RUN_NUMBER}.log 2>&1
          cat logs/dbt_run_${GITHUB_RUN_NUMBER}.log
        env:
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PORT: 5432

      - name: Commit and Push Logs
        if: always()
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -f levergreen_dbt/logs/dbt_run_${GITHUB_RUN_NUMBER}.log
          git commit -m "Add dbt build and deploy logs for run ${GITHUB_RUN_NUMBER}"
          git push -f
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

